version: '3'
services:
  webapp:
    build: ./webapp
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8000:8000

  db:
    build: ./database
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=fastapi_mysql_app
      - MYSQL_USER=ema2159
      - MYSQL_PASSWORD=12344321
      - MYSQL_ROOT_PASSWORD=12344321
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
volumes:
  db_data:
